import {StyleSheet} from 'react-native';
import {useAppSelector} from '../redux/hooks';

export const colors = {
  white: '#FFFFFF',
  orange: '#F6A80B',
  black: '#0F0A07',
  gray: '#BBBBBB',
  bluishGray: '#F8F8F8',
  secondaryGray: '#D9D9D9',
  lines: '#EAEAEA',
  blackText: '#2F2F30',
  green: '#55B88B',
  red: '#FF1C45',
  background: '#F9F9F9',
  yellowLight: '#FFEAC1',
  lightRed: '#FFDCD8',
  blue: '#397FEF',
  darkblue: '#1F3596',
  disabled: '#F4F4F4',
  iconGray: '#D0D0D0',
  borderGray: '#EFEFF0',
  greyProgram: '#919295',
  orangeBg: '#FFEAC1',
};

export const Style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  marginHorizontal: {
    marginHorizontal: 15,
  },
  button: {
    alignSelf: 'stretch',
    backgroundColor: colors.orange,
    height: 60,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  disabledButton: {
    alignSelf: 'stretch',
    backgroundColor: colors.disabled,
    height: 60,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  textInput: {
    borderRadius: 14,
    height: 50,
    fontSize: 14,
    fontFamily: 'NotoSans-Regular',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  orangeCircle: {
    height: 36,
    width: 36,
    borderRadius: 18,
    backgroundColor: colors.orange,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export const themeColors = {
  light: {
    white: '#FFFFFF',
    orange: '#F6A80B',
    black: '#0F0A07',
    gray: '#BBBBBB',
    bluishGray: '#F8F8F8',
    secondaryGray: '#D9D9D9',
    lines: '#EAEAEA',
    blackText: '#2F2F30',
    green: '#55B88B',
    red: '#FF1C45',
    background: '#F9F9F9',
    yellowLight: '#FFEAC1',
    lightRed: '#FFDCD8',
    blue: '#397FEF',
    darkblue: '#1F3596',
    disabled: '#F4F4F4',
    iconGray: '#D0D0D0',
    borderGray: '#EFEFF0',
    greyProgram: '#919295',
    orangeBg: '#FFEAC1',
    bgRadio: '#1A1A28',
    buffer: '#F8F8F8',
    skeletonBg: '#FFFFFF',
    skeletonFg: '#e6e6e6',
    bl: '#000',
    textPrimary: '#0F0A07',
    textSecondary: '#BBBBBB',
    colorMain: '#F6A80B',
    colorMainInActive: '#FFF8E9',
    input: '#F9F9F9',
    fillPrimary: '#FFFFFF',
    bgPrimary: '#FFFFFF',
    bgSecondary: '#F9F9F9',
    danger: '#FF1C45',
    bgDanger: 'rgba(234, 90, 65, 0.05)',
    borderPrimary: '#EFEFF0',
    success: '#55B88B',
  },
  dark: {
    bl: '#FFF',
    white: '#FFFFFF',
    orange: '#F6A80B',
    black: '#0F0A07',
    gray: '#BBBBBB',
    bluishGray: '#F8F8F8',
    secondaryGray: '#D9D9D9',
    lines: '#EAEAEA',
    blackText: '#2F2F30',
    green: '#55B88B',
    red: '#FF1C45',
    background: '#1E1C1C',
    yellowLight: '#FFEAC1',
    lightRed: '#FFDCD8',
    blue: '#397FEF',
    darkblue: '#1F3596',
    disabled: '#F4F4F4',
    iconGray: '#D0D0D0',
    borderGray: '#EFEFF0',
    greyProgram: '#919295',
    orangeBg: '#FFEAC1',
    bgRadio: '#1A1A28',
    buffer: '#F8F8F8',
    skeletonBg: '#2B2C2D',
    skeletonFg: '#3e454c',

    textPrimary: '#FFFFFF',
    textSecondary: '#BBBBBB',
    colorMain: '#F6A80B',
    colorMainInActive: '#31250D',
    input: '#2B2C2D',
    fillPrimary: '#1E1C1C',
    bgPrimary: '#2B2C2D',
    bgSecondary: '#0B0B0B',
    danger: '#FF1C45',
    bgDanger: '#210805',
    borderPrimary: '#31302E',
    success: '#55B88B',
  },
};

export const themeStyles = {
  light: StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: themeColors.light.bgSecondary,
    },
    marginHorizontal: {
      marginHorizontal: 15,
    },
    button: {
      alignSelf: 'stretch',
      backgroundColor: themeColors.light.colorMain,
      height: 60,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
    },
    disabledButton: {
      alignSelf: 'stretch',
      backgroundColor: themeColors.light.bgSecondary,
      height: 60,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
    },
    textInput: {
      borderRadius: 14,
      height: 50,
      fontSize: 14,
      fontFamily: 'NotoSans-Regular',
      justifyContent: 'space-between',
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'transparent',
    },
    orangeCircle: {
      height: 36,
      width: 36,
      borderRadius: 18,
      backgroundColor: themeColors.light.colorMain,
      justifyContent: 'center',
      alignItems: 'center',
    },
  }),
  dark: StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: themeColors.dark.bgSecondary,
    },
    marginHorizontal: {
      marginHorizontal: 15,
    },
    button: {
      alignSelf: 'stretch',
      backgroundColor: themeColors.dark.colorMain,
      height: 60,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
    },
    disabledButton: {
      alignSelf: 'stretch',
      backgroundColor: themeColors.dark.input,
      height: 60,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
    },
    textInput: {
      borderRadius: 14,
      height: 50,
      fontSize: 14,
      fontFamily: 'NotoSans-Regular',
      justifyContent: 'space-between',
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'transparent',
    },
    orangeCircle: {
      height: 36,
      width: 36,
      borderRadius: 18,
      backgroundColor: themeColors.dark.colorMain,
      justifyContent: 'center',
      alignItems: 'center',
    },
  }),
};

export type ColorsType = keyof typeof themeColors.light;

export const useTheme = () => {
  const {theme, text} = useAppSelector(state => state.theme);

  return {text, theme, colors: themeColors[theme], Style: themeStyles[theme]};
};
